# Generated by Django 4.1.2 on 2022-10-28 14:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categories_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_image),
        ),
    ]
